default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  hostname: localhost

development:
  <<: *default
  database: ignite_journey_development

test:
  <<: *default
  database: ignite_journey_test

production:
  <<: *default
  database: ignite_journey_production
  username: ignite_founders
  password: <%= ENV['ignite_founders_DATABASE_PASSWORD'] %>
